<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompanySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('companies')->insert([
            [
                'user_id' => 1,
                'nama' => 'PT. Maju Mundur',
                'profile' => 'Perusahaan yang bergerak di bidang teknologi informasi.',
                'business_model' => 'B2C',
                'founded_date' => '2020-01-01',
                'nama_pic' => 'Budi Santoso',
                'posisi_pic' => 'CEO',
                'telepon' => '081234567890',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Bandung',
                'jumlah_karyawan' => 50,
                'startup_summary' => 'Kami menyediakan solusi IT untuk bisnis.',
                'funding_stage' => 'seed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 2,
                'nama' => 'CV. Sukses Selalu',
                'profile' => 'Perusahaan yang fokus pada produksi barang konsumen.',
                'business_model' => 'B2B',
                'founded_date' => '2018-05-15',
                'nama_pic' => 'Siti Aminah',
                'posisi_pic' => 'Manager',
                'telepon' => '082345678901',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Timur',
                'kabupaten' => 'Surabaya',
                'jumlah_karyawan' => 100,
                'startup_summary' => 'Kami memproduksi barang berkualitas tinggi.',
                'funding_stage' => 'series_a',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 3,
                'nama' => 'PT. Teknologi Canggih',
                'profile' => 'Perusahaan yang menyediakan solusi perangkat lunak.',
                'business_model' => 'B2C',
                'founded_date' => '2021-03-10',
                'nama_pic' => 'Andi Prasetyo',
                'posisi_pic' => 'CTO',
                'telepon' => '083456789012',
                'negara' => 'Indonesia',
                'provinsi' => 'DKI Jakarta',
                'kabupaten' => 'Jakarta Selatan',
                'jumlah_karyawan' => 75,
                'startup_summary' => 'Kami mengembangkan perangkat lunak inovatif.',
                'funding_stage' => 'series_b',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 4,
                'nama' => 'CV. Bintang Jaya',
                'profile' => 'Perusahaan distribusi barang elektronik.',
                'business_model' => 'B2B',
                'founded_date' => '2019-07-20',
                'nama_pic' => 'Rina Wulandari',
                'posisi_pic' => 'Sales Manager',
                'telepon' => '084567890123',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'jumlah_karyawan' => 40,
                'startup_summary' => 'Kami mendistribusikan produk elektronik berkualitas.',
                'funding_stage' => 'series_d',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 5,
                'nama' => 'PT. Karya Abadi',
                'profile' => 'Perusahaan di bidang konstruksi dan pengembangan properti.',
                'business_model' => 'Perusahaan',
                'founded_date' => '2015-09-05',
                'nama_pic' => 'Eko Susanto',
                'posisi_pic' => 'Direktur Utama',
                'telepon' => '085678901234',
                'negara' => 'Indonesia',
                'provinsi' => 'Banten',
                'kabupaten' => 'Tangerang',
                'jumlah_karyawan' => 200,
                'startup_summary' => 'Kami mengembangkan proyek konstruksi yang berkelanjutan.',
                'funding_stage' => 'series_c',
                'created_at' => now (),
                'updated_at' => now(),
            ],
            [
                'user_id' => 6,
                'nama' => 'CV. Maju Bersama',
                'profile' => 'Perusahaan yang bergerak di bidang pertanian.',
                'business_model' => 'B2B',
                'founded_date' => '2017-11-11',
                'nama_pic' => 'Dewi Lestari',
                'posisi_pic' => 'Agronomist',
                'telepon' => '086789012345',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Bogor',
                'jumlah_karyawan' => 30,
                'startup_summary' => 'Kami mengembangkan produk pertanian yang berkelanjutan.',
                'funding_stage' => 'angel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 7,
                'nama' => 'PT. Inovasi Digital',
                'profile' => 'Perusahaan yang fokus pada pengembangan aplikasi mobile.',
                'business_model' => 'B2C',
                'founded_date' => '2022-01-01',
                'nama_pic' => 'Fajar Pramono',
                'posisi_pic' => 'Product Manager',
                'telepon' => '087890123456',
                'negara' => 'Indonesia',
                'provinsi' => 'DI Yogyakarta',
                'kabupaten' => 'Yogyakarta',
                'jumlah_karyawan' => 25,
                'startup_summary' => 'Kami mengembangkan aplikasi mobile yang inovatif.',
                'funding_stage' => 'seed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 8,
                'nama' => 'CV. Berkah Abadi',
                'profile' => 'Perusahaan yang bergerak di bidang perdagangan.',
                'business_model' => 'B2B',
                'founded_date' => '2016-03-15',
                'nama_pic' => 'Sri Wulandari',
                'posisi_pic' => 'Purchasing Manager',
                'telepon' => '088901234567',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Timur',
                'kabupaten' => 'Malang',
                'jumlah_karyawan' => 60,
                'startup_summary' => 'Kami memperdagangkan produk yang berkualitas.',
                'funding_stage' => 'series_a',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 9,
                'nama' => 'PT. Teknologi Informasi',
                'profile' => 'Perusahaan yang menyediakan solusi perangkat keras.',
                'business_model' => 'Perusahaan',
                'founded_date' => '2014-06-01',
                'nama_pic' => 'Rudi Hartono',
                'posisi_pic' => 'Direktur Teknologi',
                'telepon' => '081234567890',
                'negara' => 'Indonesia',
                'provinsi' => 'Bali',
                'kabupaten' => 'Denpasar',
                'jumlah_karyawan' => 150,
                'startup_summary' => 'Kami menyediakan solusi perangkat keras yang berkelanjutan.',
                'funding_stage' => 'series_b',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 10,
                'nama' => 'CV. Jaya Abadi',
                'profile' => 'Perusahaan yang bergerak di bidang konstruksi.',
                'business_model' => 'B2B',
                'founded_date' => '2013-09-10',
                'nama_pic' => 'Tono Sudarto',
                'posisi_pic' => 'Project Manager',
                'telepon' => '082345678901',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Bandung',
                'jumlah_karyawan' => 80,
                'startup_summary' => 'Kami mengembangkan proyek konstruksi yang berkelanjutan.',
                'funding_stage' => 'series_a',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 11,
                'nama' => 'PT. Karya Mandiri',
                'profile' => 'Perusahaan yang fokus pada pengembangan aplikasi web.',
                'business_model' => 'B2C',
                'founded_date' => '2020-05-01',
                'nama_pic' => 'Rizki Widyanto',
                'posisi_pic' => 'CTO',
                'telepon' => '083456789012',
                'negara' => 'Indonesia',
                'provinsi' => 'DKI Jakarta',
                'kabupaten' => 'Jakarta Selatan',
                'jumlah_karyawan' => 90,
                'startup_summary' => 'Kami mengembangkan aplikasi web yang inovatif.',
                'funding_stage' => 'series_a',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 12,
                'nama' => 'CV. Sukses Bersama',
                'profile' => 'Perusahaan yang bergerak di bidang perdagangan.',
                'business_model' => 'B2B',
                'founded_date' => '2012-07-20',
                'nama_pic' => 'Dwi Wahyu',
                'posisi_pic' => 'Sales Manager',
                'telepon' => '084567890123',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'jumlah_karyawan' => 45,
                'startup_summary' => 'Kami memperdagangkan produk yang berkualitas.',
                'funding_stage' => 'angel',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 13,
                'nama' => 'PT. Teknologi Cerdas',
                'profile' => 'Perusahaan yang fokus pada pengembangan aplikasi artificial intelligence.',
                'business_model' => 'B2C',
                'founded_date' => '2021-09-01',
                'nama_pic' => 'Eko Prasetyo',
                'posisi_pic' => 'Product Manager',
                'telepon' => '085678901234',
                'negara' => 'Indonesia',
                'provinsi' => 'DI Yogyakarta',
                'kabupaten' => 'Yogyakarta',
                'jumlah_karyawan' => 35,
                'startup_summary' => 'Kami mengembangkan aplikasi AI yang inovatif.',
                'funding_stage' => 'seed',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 14,
                'nama' => 'CV. Berkah Jaya',
                'profile' => 'Perusahaan yang bergerak di bidang konstruksi.',
                'business_model' => 'B2B',
                'founded_date' => '2011-11-11',
                'nama_pic' => 'Siti Aminah',
                'posisi_pic' => 'Project Manager',
                'telepon' => '086789012345',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Bogor',
                'jumlah_karyawan' => 55,
                'startup_summary' => 'Kami mengembangkan proyek konstruksi yang berkelanjutan.',
                'funding_stage' => 'series_a',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 15,
                'nama' => 'PT. Inovasi Teknologi',
                'profile' => 'Perusahaan yang fokus pada pengembangan aplikasi mobile.',
                'business_model' => 'B2C',
                'founded_date' => '2022-03-01',
                'nama_pic' => 'Fajar Pramono',
                'posisi_pic' => 'CTO',
                'telepon' => '087890123456',
                'negara' => 'Indonesia',
                'provinsi' => 'DKI Jakarta',
                'kabupaten' => 'Jakarta Selatan',
                'jumlah_karyawan' => 65,
                'startup_summary' => 'Kami mengembangkan aplikasi mobile yang inovatif.',
                'funding_stage' => 'series_b',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 16,
                'nama' => 'CV. Jaya Mandiri',
                'profile' => 'Perusahaan yang bergerak di bidang perdagangan.',
                'business_model' => 'B2B',
                'founded_date' => '2010-09-10',
                'nama_pic' => 'Rudi Hartono',
                'posisi_pic' => 'Purchasing Manager',
                'telepon' => '088901234567',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Timur',
                'kabupaten' => 'Malang',
                'jumlah_karyawan' => 70,
                'startup_summary' => 'Kami memperdagangkan produk yang berkualitas.',
                'funding_stage' => 'series_a',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 17,
                'nama' => 'PT. Karya Teknologi',
                'profile' => 'Perusahaan yang fokus pada pengembangan aplikasi web.',
                'business_model' => 'B2C',
                'founded_date' => '2021-01-01',
                'nama_pic' => 'Tono Sudarto',
                'posisi_pic' => 'Product Manager',
                'telepon' => '081234567890',
                'negara' => 'Indonesia',
                'provinsi' => 'Bali',
                'kabupaten' => 'Denpasar',
                'jumlah_karyawan' => 85,
                'startup_summary' => 'Kami mengembangkan aplikasi web yang inovatif.',
                'funding_stage' => 'series_b',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 18,
                'nama' => 'CV. Sukses Abadi',
                'profile' => 'Perusahaan yang bergerak di bidang konstruksi.',
                'business_model' => 'B2B',
                'founded_date' => '2009-11-11',
                'nama_pic' => 'Dwi Wahyu',
                'posisi_pic' => 'Project Manager',
                'telepon' => '082345678901',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Barat',
                'kabupaten' => 'Bandung',
                'jumlah_karyawan' => 95,
                'startup_summary' => 'Kami mengembangkan proyek konstruksi yang berkelanjutan.',
                'funding_stage' => 'series_a',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 19,
                'nama' => 'PT. Teknologi Inovatif',
                'profile' => 'Perusahaan yang fokus pada pengembangan aplikasi artificial intelligence.',
                'business_model' => 'B2C',
                'founded_date' => '2022-05-01',
                'nama_pic' => 'Eko Prasetyo',
                'posisi_pic' => 'CTO',
                'telepon' => '083456789012',
                'negara' => 'Indonesia',
                'provinsi' => 'DI Yogyakarta',
                'kabupaten' => 'Yogyakarta',
                'jumlah_karyawan' => 105,
                'startup_summary' => 'Kami mengembangkan aplikasi AI yang inovatif.',
                'funding_stage' => 'series_b',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 20,
                'nama' => 'CV. Berkah Mandiri',
                'profile' => 'Perusahaan yang bergerak di bidang perdagangan.',
                'business_model' => 'B2B',
                'founded_date' => '2008-09-10',
                'nama_pic' => 'Siti Aminah',
                'posisi_pic' => 'Sales Manager',
                'telepon' => '084567890123',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Tengah',
                'kabupaten' => 'Semarang',
                'jumlah_karyawan' => 115,
                'startup_summary' => 'Kami memperdagangkan produk yang berkualitas.',
                'funding_stage' => 'series_a',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
