<?php

namespace Database\Seeders;

use App\Models\Investor;
use Illuminate\Database\Seeder;

class InvestorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $investors = [
            [
                'org_name' => 'Graham Ltd',
                'number_of_contacts' => 41,
                'location' => 'Robelborough',
                'description' => 'Inventore tempore vero debitis sequi exercitationem maxime.',
                'investment_stage' => 'Seed',
                'investor_type' => 'Angel',
                'user_id' => 1,
            ],
            [
                'org_name' => 'Tech Innovators',
                'number_of_contacts' => 30,
                'location' => 'Tech City',
                'description' => 'Leading the way in tech innovations.',
                'investment_stage' => 'Series A',
                'investor_type' => 'Venture Capital',
                'user_id' => 1,
            ],
            [
                'org_name' => 'Green Ventures',
                'number_of_contacts' => 25,
                'location' => 'Eco Town',
                'description' => 'Investing in sustainable projects.',
                'investment_stage' => 'Series B',
                'investor_type' => 'Private Equity',
                'user_id' => 2,
            ],
            [
                'org_name' => 'Health Investments',
                'number_of_contacts' => 18,
                'location' => 'Med City',
                'description' => 'Focused on healthcare startups.',
                'investment_stage' => 'Pre-Seed',
                'investor_type' => 'Angel',
                'user_id' => 2,
            ],
            [
                'org_name' => 'EduFund',
                'number_of_contacts' => 12,
                'location' => 'Learning Hub',
                'description' => 'Investing in education technology.',
                'investment_stage' => 'Seed',
                'investor_type' => 'Venture Capital',
                'user_id' => 3,
            ],
            [
                'org_name' => 'Fintech Partners',
                'number_of_contacts' => 20,
                'location' => 'Finance District',
                'description' => 'Empowering financial technology solutions.',
                'investment_stage' => 'Series A',
                'investor_type' => 'Venture Capital',
                'user_id' => 3,
            ],
            [
                'org_name' => 'Foodie Investors',
                'number_of_contacts' => 15,
                'location' => 'Culinary Capital',
                'description' => 'Investing in food and beverage startups.',
                'investment_stage' => 'Series B',
                'investor_type' => 'Private Equity',
                'user_id' => 4,
            ],
            [
                'org_name' => 'Travel Ventures',
                'number_of_contacts' => 10,
                'location' => 'Tourist City',
                'description' => 'Investing in travel and tourism businesses.',
                'investment_stage' => 'Pre-Seed',
                'investor_type' => 'Angel',
                'user_id' => 4,
            ],
            [
                'org_name' => 'Real Estate Investors',
                'number_of_contacts' => 22,
                'location' => 'Property Town',
                'description' => 'Focusing on real estate development.',
                'investment_stage' => 'Series A',
                'investor_type' => 'Private Equity',
                'user_id' => 5,
            ],
            [
                'org_name' => 'Energy Solutions',
                'number_of_contacts' => 14,
                'location' => 'Energy City',
                'description' => 'Investing in renewable energy projects.',
                'investment_stage' => 'Seed',
                'investor_type' => 'Venture Capital',
                'user_id' => 5,
            ],
            [
                'org_name' => 'Retail Innovators',
                'number_of_contacts' => 19,
                'location' => 'Shopping District',
                'description' => 'Investing in retail technology.',
                'investment_stage' => 'Series B',
                'investor_type' => 'Angel',
                'user_id' => 6,
            ],
            [
                'org_name' => 'Blockchain Ventures',
                'number_of_contacts' => 11,
                'location' => 'Crypto Valley',
                'description' => 'Investing in blockchain technology.',
                'investment_stage' => 'Pre-Seed',
                'investor_type' => 'Venture Capital',
                'user_id' => 6,
            ],
            [
                'org_name' => 'Media Investors',
                'number_of_contacts' => 16,
                'location' => 'Media City',
                'description' => 'Investing in media and entertainment startups.',
                'investment_stage' => 'Series A',
                'investor_type' => 'Private Equity',
                'user_id' => 7,
            ],
            [
                'org_name' => 'Logistics Partners',
                'number_of_contacts' => 13,
                'location' => 'Logistics Hub',
                'description' => 'Investing in logistics and supply chain solutions.',
                'investment_stage' => 'Seed',
                'investor_type' => 'Venture Capital',
                'user_id' => 7,
            ],
            [
                'org_name' => 'Cybersecurity Ventures',
                'number_of_contacts' => 17,
                'location' => 'Cyber City',
                'description' => 'Investing in cybersecurity startups.',
                'investment_stage' => 'Series B',
                'investor_type' => 'Angel',
                'user_id' => 8,
            ],
            [
                'org_name' => 'Environmental Solutions',
                'number_of_contacts' => 21,
                'location' => 'Eco City',
                'description' => 'Investing in environmental sustainability projects.',
                'investment_stage' => 'Pre-Seed',
                'investor_type' => 'Venture Capital',
                'user_id' => 8,
            ],
            [
                'org_name' => 'Healthcare Ventures',
                'number_of_contacts' => 24,
                'location' => 'Med City',
                'description' => 'Investing in healthcare startups.',
                'investment_stage' => 'Series A',
                'investor_type' => 'Private Equity',
                'user_id' => 9,
            ],
            [
                'org_name' => 'Financial Solutions',
                'number_of_contacts' => 26,
                'location' => 'Finance District',
                'description' => 'Investing in financial technology startups.',
                'investment_stage' => 'Seed',
                'investor_type' => 'Venture Capital',
                'user_id' => 9,
            ],
            [
                'org_name' => 'Education Innovators',
                'number_of_contacts' => 28,
                'location' => 'Learning Hub',
                'description' => 'Investing in education technology startups.',
                'investment_stage' => 'Series B',
                'investor_type' => 'Angel',
                'user_id' => 10,
            ],
            [
                'org_name' => 'Real Estate Developers',
                'number_of_contacts' => 32,
                'location' => 'Property Town',
                'description' => 'Investing in real estate development projects.',
                'investment_stage' => 'Pre-Seed',
                'investor_type' => 'Venture Capital',
                'user_id' => 10,
            ],
            [
                'org_name' => 'Energy Innovators',
                'number_of_contacts' => 35,
                'location' => 'Energy City',
                'description' => 'Investing in renewable energy startups.',
                'investment_stage' => 'Series A',
                'investor_type' => 'Private Equity',
                'user_id' => 11,
            ],
            [
                'org_name' => 'Retail Ventures',
                'number_of_contacts' => 38,
                'location' => 'Shopping District',
                'description' => 'Investing in retail technology startups.',
                'investment_stage' => 'Seed',
                'investor_type' => 'Venture Capital',
                'user_id' => 11,
            ],
            [
                'org_name' => 'Blockchain Innovators',
                'number_of_contacts' => 40,
                'location' => 'Crypto Valley',
                'description' => 'Investing in blockchain technology startups.',
                'investment_stage' => 'Series B',
                'investor_type' => 'Angel',
                'user_id' => 12,
            ],
            [
                'org_name' => 'Media Ventures',
                'number_of_contacts' => 42,
                'location' => 'Media City',
                'description' => 'Investing in media and entertainment startups.',
                'investment_stage' => 'Pre-Seed',
                'investor_type' => 'Venture Capital',
                'user_id' => 12,
            ],
            [
                'org_name' => 'Logistics Solutions',
                'number_of_contacts' => 45,
                'location' => 'Logistics Hub',
                'description' => 'Investing in logistics and supply chain solutions.',
                'investment_stage' => 'Series A',
                'investor_type' => 'Private Equity',
                'user_id' => 13,
            ],
            [
                'org_name' => 'Cy bersecurity Solutions',
                'number_of_contacts' => 48,
                'location' => 'Cyber City',
                'description' => 'Investing in cybersecurity startups.',
                'investment_stage' => 'Seed',
                'investor_type' => 'Venture Capital',
                'user_id' => 13,
            ],
            [
                'org_name' => 'Environmental Ventures',
                'number_of_contacts' => 50,
                'location' => 'Eco City',
                'description' => 'Investing in environmental sustainability projects.',
                'investment_stage' => 'Series B',
                'investor_type' => 'Angel',
                'user_id' => 14,
            ],
        ];

        foreach ($investors as $investor) {
            Investor::create($investor);
        }
    }
}
