<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'nama_depan' => 'Budi',
                'nama_belakang' => 'Santoso',
                'email' => 'budi.santoso@example.com',
                'pekerjaan' => 'Software Engineer',
                'instansi' => 'PT. Maju Mundur',
                'img' => 'profile1.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'), // Ganti dengan password yang aman
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123456',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Barat',
                'alamat' => 'Jl. Raya No. 1, Bandung',
                'telepon' => '081234567890',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Siti',
                'nama_belakang' => 'Aminah',
                'email' => 'siti.aminah@example.com',
                'pekerjaan' => 'Marketing Manager',
                'instansi' => 'CV. Sukses Selalu',
                'img' => 'profile2.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123457',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Timur',
                'alamat' => 'Jl. Mawar No. 2, Surabaya',
                'telepon' => '082345678901',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Andi',
                'nama_belakang' => 'Prasetyo',
                'email' => 'andi.prasetyo@example.com',
                'pekerjaan' => 'Designer',
                'instansi' => 'PT. Kreatif Indonesia',
                'img' => 'profile3.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123458',
                'negara' => 'Indonesia',
                'provinsi' => 'DKI Jakarta',
                'alamat' => 'Jl. Kebon Jeruk No. 3, Jakarta',
                'telepon' => '083456789012',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Rina',
                'nama_belakang' => 'Wulandari',
                'email' => 'rina.wulandari@example.com',
                'pekerjaan' => 'Product Manager',
                'instansi' => 'PT. Inovasi Digital',
                'img' => 'profile4.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123459',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Tengah',
                'alamat' => 'Jl. Merah No. 4, Semarang',
                'telepon' => '084567890123',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Eko',
                'nama_belakang' => 'Susanto',
                'email' => 'eko.susanto@example.com',
                'pekerjaan' => 'Data Analyst',
                'instansi' => ' CV. Bintang Jaya',
                'img' => 'profile5.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123460',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Barat',
                'alamat' => 'Jl. Raya No. 2, Bandung',
                'telepon' => '085678901234',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Dwi',
                'nama_belakang' => 'Wahyudi',
                'email' => 'dwi.wahyudi@example.com',
                'pekerjaan' => 'Software Engineer',
                'instansi' => 'PT. Teknologi Cerdas',
                'img' => 'profile6.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123461',
                'negara' => 'Indonesia',
                'provinsi' => 'DI Yogyakarta',
                'alamat' => 'Jl. Mawar No. 3, Yogyakarta',
                'telepon' => '086789012345',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Tono',
                'nama_belakang' => 'Sudarto',
                'email' => 'tono.sudarto1@example.com',
                'pekerjaan' => 'Marketing Manager',
                'instansi' => 'CV. Sukses Bersama',
                'img' => 'profile7.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123462',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Timur',
                'alamat' => 'Jl. Kebon Jeruk No. 4, Surabaya',
                'telepon' => '087890123456',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Rudi',
                'nama_belakang' => 'Hartono',
                'email' => 'rudi.hartono1@example.com',
                'pekerjaan' => 'Designer',
                'instansi' => 'PT. Kreatif Indonesia',
                'img' => 'profile8.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123463',
                'negara' => 'Indonesia',
                'provinsi' => 'DKI Jakarta',
                'alamat' => 'Jl. Raya No. 5, Jakarta',
                'telepon' => '088901234567',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Siti',
                'nama_belakang' => 'Aminah',
                'email' => 'siti.aminah1@example.com',
                'pekerjaan' => 'Product Manager',
                'instansi' => 'PT. Inovasi Digital',
                'img' => 'profile9.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123464',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Tengah',
                'alamat' => 'Jl. Merah No. 5, Semarang',
                'telepon' => '089012345678',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Eko',
                'nama_belakang' => 'Prasetyo',
                'email' => 'eko.prasetyo1@example.com',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'CV. Bintang Jaya',
                'img' => 'profile10.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123465',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Barat',
                'alamat' => 'Jl. Raya No. 6, Bandung',
                'telepon' => '090123456789',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Dwi',
                'nama_belakang' => 'Wahyudi',
                'email' => 'dwi.wahyudi1@example.com',
                'pekerjaan' => 'Software Engineer',
                'instansi' => 'PT. Teknologi Cerdas',
                'img' => 'profile11.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123466',
                'negara' => 'Indonesia',
                'provinsi' => 'DI Yogyakarta',
                'alamat' => 'Jl. Mawar No. 6, Yogyakarta',
                'telepon' => '091234567890',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Tono',
                'nama_belakang' => 'Sudarto',
                'email' => 'tono.sudarto2@example.com',
                'pekerjaan' => 'Marketing Manager',
                'instansi' => 'CV. Sukses Bersama',
                'img' => 'profile12.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123467',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Timur',
                'alamat' => 'Jl. Kebon Jeruk No. 7, Surabaya',
                'telepon' => '092345678901',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Rudi',
                'nama_belakang' => 'Hartono',
                'email' => 'rudi.hartono2@example.com',
                'pekerjaan' => 'Designer',
                'instansi' => 'PT. Kreatif Indonesia',
                'img' => 'profile13.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123468',
                'negara' => 'Indonesia',
                'provinsi' => 'DKI Jakarta',
                'alamat' => 'Jl. Raya No. 8, Jakarta',
                'telepon' => '093456789012',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Siti',
                'nama_belakang' => 'Aminah',
                'email' => 'siti.aminah2@example.com',
                'pekerjaan' => 'Product Manager',
                'instansi' => 'PT. Inovasi Digital',
                'img' => 'profile14.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123469',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Tengah',
                'alamat' => 'Jl. Merah No. 8, Semarang',
                'telepon' => '094567890123',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Eko',
                'nama_belakang' => 'Prasetyo',
                'email' => 'eko.prasetyo2@example.com',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'CV. Bintang Jaya',
                'img' => 'profile15.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123470',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Barat',
                'alamat' => 'Jl. Raya No. 9, Bandung',
                'telepon' => '095678901234',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Dwi',
                'nama_belakang' => 'Wahyudi',
                'email' => 'dwi.wahyudi2@example.com',
                'pekerjaan' => 'Software Engineer',
                'instansi' => 'PT. Teknologi Cerdas',
                'img' => 'profile16.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123471',
                'negara' => 'Indonesia',
                'provinsi' => 'DI Yogyakarta',
                'alamat' => 'Jl. Mawar No. 9, Yogyakarta',
                'telepon' => '096789012345',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Tono',
                'nama_belakang' => 'Sudarto',
                'email' => 'tono.sudarto3@example.com',
                'pekerjaan' => 'Marketing Manager',
                'instansi' => 'CV. Sukses Bersama',
                'img' => 'profile17.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123472',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Timur',
                'alamat' => 'Jl. Kebon Jeruk No. 10, Surabaya',
                'telepon' => '097890123456',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Rudi',
                'nama_belakang' => 'Hartono',
                'email' => 'rudi.hartono3@example.com',
                'pekerjaan' => 'Designer',
                'instansi' => 'PT. Kreatif Indonesia',
                'img' => 'profile18.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123473',
                'negara' => 'Indonesia',
                'provinsi' => 'DKI Jakarta',
                'alamat' => 'Jl. Raya No. 11, Jakarta',
                'telepon' => '098901234567',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Siti',
                'nama_belakang' => 'Aminah',
                'email' => 'siti.aminah3@example.com',
                'pekerjaan' => 'Product Manager',
                'instansi' => 'PT. Inovasi Digital',
                'img' => 'profile19.jpg',
                'email_verified_at' => now(),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123474',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Tengah',
                'alamat' => 'Jl. Merah No. 11, Semarang',
                'telepon' => '099012345678',
                'role' => 'USER',
            ],
            [
                'nama_depan' => 'Eko',
                'nama_belakang' => 'Prasetyo',
                'email' => 'eko.prasetyo3@example.com',
                'pekerjaan' => 'Data Analyst',
                'instansi' => 'CV. Bintang Jaya',
                'img' => 'profile20.jpg',
                'email_verified_at' => now (),
                'password' => bcrypt('password123'),
                'created_at' => now(),
                'updated_at' => now(),
                'nik' => '1234567890123475',
                'negara' => 'Indonesia',
                'provinsi' => 'Jawa Barat',
                'alamat' => 'Jl. Raya No. 12, Bandung',
                'telepon' => '100123456789',
                'role' => 'USER',
            ],
        ]);
    }
}
